# HASH BREAKDOWN by Silvia Binda Heiserova
# 2024

# This database was created using an automated internet search of the term "feminism is" in python using Duck duck go search engine on March 5th 2024.
# to see the original html file that was parsed see the file "feminism_is_search_DuckDuckGo.html"
# for more details of the parsing and database cleaning process see the file "data_set_extraction.ipynb" 

# This pyhton database is used in the main code of Hash Breakdown.
# This file was last time edited on: 29/03/2024

database_feminism = [
"Although largely originating in the West, feminism is manifested worldwide and is represented by various institutions committed to activity on behalf of women's rights and interests.",
"Feminism is a range of socio-political movements and ideologies that aim to define and establish the political, economic, personal, and social equality of the sexes.",
"Feminism is a complex set of ideologies and theories, that at its core seeks to achieve equal social, political, and economic rights for women.",
"At its core, feminism is the belief that women deserve equal social, economic, and political rights and freedoms.",
"Feminism is the belief in the equality of people of all genders, a set of values aimed at dismantling gender inequality and the structures that uphold it.",
"Quite simply, feminism is about all genders having equal rights and opportunities.",
"A majority of Americans (64%) say feminism is empowering and 42% see it as inclusive.",
"Feminism is said to be the movement to end women's oppression (hooks 2000, 26).",
"Feminism is an ideological and political movement that seeks equality and equity for women in all aspects, including social, political, personal, and economic realms.",
"Feminism is a term that is controversial - although, it really shouldn't be.",
"Feminism is a social, political, and economic movement.",
"Feminism is about changing the way that people see male and female rights (mainly female), and campaigning for equal ones.",
"Somebody who follows feminism is called a feminist.",
"As this entry describes, feminism is both an intellectual commitment and a political movement that seeks justice for women and the end of sexism in all forms.",
"Marxist feminism is a branch of feminist theory which argues that the main cause of women's oppression is capitalism.",
"This type of feminism is based on the understandings of Marxism, proposed by Karl Marx and collaborator Friedrich Engels in the 19th century.",
"Black feminist scholars including hooks, Audre Lorde, and Angela Davis make clear that feminism is about systems of power, which include (and are not limited to) sexism.",
"Basically, feminism is a philosophy that advocates equal rights for women and men—socially, politically, economically, and in other ways.",
"Feminism is a movement that seeks to advance the rights and status of women and create a more just and equal society.",
"Fourth-wave feminism is a feminist movement that began around the early 2010s and is characterized by a focus on the empowerment of women, the use of internet tools, and intersectionality.",
"FEMINISM IS… emphasizes that choice is the most important part of feminism, which is important for a novel about feminism.",
"FEMINISM IS… by Alexandra Black, Laura Buller, Emily Hoyle and Dr. Megan Todd is a great book that everyone should read.",
"Hood Feminism is replete with examples of when such solidarity has been lacking.",
"Feminism is a dynamic philosophy and social movement that advocates for human rights and gender equality.",
"Feminism is grounded on the belief that women are oppressed or disadvantaged by comparison with men, and that their oppression is in some way illegitimate or unjustified.",
"Feminism is for Everybody.",
"Everyday Feminism is an educational platform for personal and social liberation.",
"Feminism is a subset of egalitarianism; the two are not mutually exclusive.",
"Feminism is NOT about pitting men against women, and we acknowledge that yes, men have problems too.",
"Although feminism is a common cultural and theoretical heritage, which cannot be possessed, current invocations of feminist identity use possessive expressions of feminism to illustrate the individuality and diversity of feminism (Cardona & Colbert, Citation 1997; Ms. Foundation, Citation 2016).",
"For some, feminism is a theory or ideology about unequal and oppressive gender relations.",
"For most feminists, however, feminism is a political practice - a desire to change the world.",
"Choice feminism is a critical term for expressions of feminism that emphasize women's freedom of choice.",
"Feminism history and perspective - from history to herstory Feminism is a collection of movements and ideologies aimed at defining, establishing, and defending equal political, economic, and social rights for women.",
"Feminism Is Sensational.",
"Feminism is not a stick with which to beat other women with.",
"Feminism is a word that means equal rights for women.",
"Equality feminism is a subset of the overall feminism movement and more specifically of the liberal feminist tradition that focuses on the basic similarities between men and women, and whose ultimate goal is the equality of both genders in all domains.",
"Feminism is one of the oldest movements in global history.",
"Andi Zeisler, 41, a founder of the feminist pop culture magazine Bitch, said, 'Just the fact that these questions are being asked shows that feminism is a lot more accepted.'",
"Lesbian feminism is a cultural movement and critical perspective that encourages women to focus their efforts, attentions, relationships, and activities towards their fellow women rather than men, and often advocates lesbianism as the logical result of feminism.",
"Feminism Is for Everybody (2000) by bell hooks is an enlightening exploration of feminism and why it is important for everyone.",
"Today we recognize that true feminism is the true equality of both sexes, without it being limited or restricted.",
"My feminism is black, intersectional, and womanist.",
"Feminism is a movement primarily associated with white Western women's mobilisations around their rights, historically spanning from suffrage, equal pay through to reproductive and sexual rights.",
"Feminism is the path to achieve gender equality and women's rights.",
"Feminism is about collectively and actively transforming systems of oppression so that women, men and gender non-conforming people hold equal power, resources and rights.",
"To her, feminism is the belief that 'women and men are inherently of equal worth.'.",
"Feminism is changing.",
"Feminism is straying from its path and taking a nasty route.",
"Feminism is knowing that you don't have to wear things to impress a man.",
"Feminism is also knowing that it's okay to wear things to impress a man if you want to.",
"Cultural feminism is a branch of feminism that argues there are innate differences between men and women.",
"Feminism is the movement to end women's oppression and to help women achieve full social, political, familial, and financial equality with men.",
"Feminism is still a very relevant movement because, despite what the media will tell you, things are still not equal.",
"A movement of powerful women can seem threatening to a patriarchal society, but feminism is misunderstood and needs to be reclaimed.",
"Feminism is the result of people throughout history getting together to create and demand change so that girls and women would have rights equal to boys and men.",
"Feminism is multicultural and diasporic.",
"Feminism is a social movement ideology that articulates gendered oppression.",
"Feminism is aimed at defining, establishing, and defending a state of equal political, economic, cultural, and social rights for women.",
"Feminism is defined as the belief in the social, political, and economic equality of the sexes.",
"The goal of feminism is to challenge the systemic inequalities women face on a daily basis.",
"Feminism is a social, political, and cultural movement that advocates for gender equality and the rights of women.",
"Next on our list of types of feminism is radical feminism.",
"As the name suggests, radical feminism is a branch of feminism that emphasizes on radical reordering of society.",
"Feminism Is About De-Centering the Male Perspective .",
"Islamic feminism is a form of feminism concerned with the role of women in Islam.",
"Feminism is a series of social movements, political movements, and philosophies aimed at identifying, developing, and achieving gender, political, cultural, personal, and social equality.",
"Feminism is a collection of movements aimed at defining, establishing, and defending equal political, economic, and social rights for women.",
"Christian feminism is a school of Christian theology which uses the viewpoint of a Christian to promote and understand morally, socially, and spiritually the equality of men and women.",
"Many women are reasserting that feminism is a necessary social movement for the equality and liberation of all women, not just platitudes about choices for some.",
"The history of feminism is a complicated topic, but the ideology itself is simple.",
"Ecofeminism is a branch of feminism and political ecology.",
"Feminism is more than a noun — it's a process.",
"Data Feminism is a book written by Catherine D'Ignazio and Lauren F. Klein as part literature review, part call to action, Data Feminism provides a framework for data scientists seeking to learn how feminism can help them work toward justice, and for feminists who want to focus their efforts on the growing field of data science.",
"A common American term for third-wave feminism is 'grrl feminism,' and in Europe it is known as 'new feminism.",
"Loosely defined, Indigenous feminism is an intersectional theory and practice of feminism that focuses on decolonization, Indigenous sovereignty, and human rights for Indigenous women and their families.",
"Feminism is simple.",
"Chicana feminism is a sociopolitical movement, theory, and praxis that scrutinizes the historical, cultural, spiritual, educational, and economic intersections impacting Chicanas and the Chicana/o community in the United States.",
"The definition of feminism is 'the advocacy of women's rights on the basis of the equality of the sexes'.",
"A lot of people are under the impression, I think, that feminism is a movement to make females elite or maybe to take away men's rights.",
"Feminism is an interesting concept, and has been the base of the fight for equality of women in society since the nineteenth century.",
"Feminism is defined as the belief in the social, political, and economic equality of the sexes.",
"The goal of feminism is to challenge the systemic inequalities women face on a daily basis.",
"Islamic feminism is a form of feminism concerned with the role of women in Islam.",
"Feminism is for everyone-men and women alike.",
"Feminism is about creating equality between men and women and those who do not fit the binary molds of society.",
"Marxist feminism is a strand of feminist theory that grounds its perspective in Karl Marx' work on capitalism.",
"Maternal feminism is the belief of many early feminists that women as mothers and caregivers had an important but distinctive role to play in society and in politics.",
"This saw a change in postfeminist sensibility, whereby feminism is no longer refuted to 'count' as feminine.",
"The second wave of feminism is the period of the women's movement in the United States that emerged in the 1960s and lasted through the 1970s.",
"Feminism is the set of beliefs and ideas that belong to the broad social and political movement to achieve greater equality for women.",
"The misinformation regarding feminism is startling.",
"The belief that feminism is just a bunch of crazy women saying that men are monstrous creatures and are inferior is beyond mistaken.",
"Feminism is an evil agenda of Luciferians, whose intent is to destroy the family unit, destabilize U.S. society, and destroy America as part of achieving World Government.",
"As a philosophy, feminism is fundamentally about female empowerment, combatting sexism, and shoring up women's rights.",
"Postmodern feminism is a mix of post-structuralism, postmodernism, and French feminism.",
"So begins Feminism is for Everybody, a short, accessible introduction to feminist theory by one of its most influential practitioners.",
"Feminism is a force that attempts to unravel the sexist framework of our society, and as a result, has been met with a certain amount of opposition.",
"Cultural feminism is a variety of feminism which emphasizes essential differences between men and women, based on biological differences in reproductive capacity.",
"A common critique of today's feminism is that it has 'gone too far'.",
"Although largely originating in the West, feminism is manifested worldwide and is represented by various institutions committed to activity on behalf of women's rights and interests.",
"Feminism is supposed to ease some of the dissonance between what women want and what they feel they're supposed to want.",
"Feminism is for everybody.",
"Radical feminism is a branch of feminism that seeks to dismantle the traditional patriarchal power and gender roles that keep women oppressed.",
"Feminism is a collection of movements and ideologies aimed at defining, establishing, and defending equal political, economic, and social justice for women.",
"A fundamental concept underlying feminism is that women are an oppressed group, a reality that feminism seeks to highlight and fight against.",
"Feminism is rooted in ending men's historical power over women.",
"Feminism is still very much engaged in the battle for hearts and minds; appealing to the sense of humor of a very small minority of the population can be a good way to alienate the rest.",
"Feminism is a movement that advocates for the social, political, and economic equality of the sexes.",
"Seen from this perspective, feminism is everyone's business, requiring a whole-of-society approach.",
"Perhaps the most common objection to feminism is the argument that it is unnecessary, because equality has already been achieved.",
"Black Feminism is an intellectual, artistic, and philosophical tradition and activist tradition and practice grounded in African American women's lived experiences.",
"On the surface, the definition of feminism is simple.",
"In areas where women have a clear advantage, feminism is either silent or actively opposing reform (eg.",
"To that end, we present this data-driven argument that feminism is a substantial cause of unhappiness and dysfunction in America.",
"Feminism is not homogenous.",
"Feminism is the ideology that is driving our civilizational decay.",
"Feminism is a socio-political movement that centers around the idea of improving the living standards and cultural opinion of women, both through changing female representation in the media and legislation.",
"Black Women and Feminism and The Feminist Theory in which she declared, 'Feminism is a movement to end sexism, sexist exploitation and oppression.'",
"Radical feminism is perhaps the most misunderstood branch of feminism.",
"Global feminism is a feminist theory closely aligned with post-colonial theory and postcolonial feminism.",
"Marxist feminism is a philosophical variant of feminism that incorporates and extends Marxist theory.",
"Ecofeminism is an ideology and movement that sees climate change, gender equality, and social injustice more broadly as intrinsically related issues, all tied to masculine dominance in society.",
"Standpoint feminism is a theory that feminist social science should be practiced from the standpoint of women or particular groups of women, as some scholars (e.g.",
"Feminism is NOT a movement aimed at destroying men, but at destroying the patriarchal ideas that are cemented in society.",
"Feminism is NOT aimed at making men lesser than women, but at improving the status of being a woman so that it's equal to that of being a man.",
"Feminism is Evil.",
"Feminism is about female supremacy, not gender equality.",
"Feminism is generally split up into three 'waves'.",
"As a movement, feminism is a multi-faceted series of political ideologies, economic theories, and social identities spanning hundreds of years.",
"Equality, Ending women violence, and much more but in all reality feminism is all of that.",
"Needs help debating that feminism is a harmful ideology.",
"Reactionary feminism is a form of feminism that rejects the progressivist belief that human history is an ongoing arc of moral advancement and seeks to ground a defence of women's interests in a contingent, materialist, and sex-realist position.",
"Feminism is a Religion - and Its God is Man.",
"In an eloquent piece last Tuesday, Dr Janice Fiamengo, Professor of English at the University of Ottawa, Canada, made the case that feminism is a religion.",
"Jewish feminism is a movement that seeks to make the religious, legal, and social status of Jewish women equal to that of Jewish men in Judaism.",
"In other words, feminism is a commitment to achieving the equality of the sexes.",
"Intersectional feminism is a type of feminism focused on the fact that systems of oppression impact people differently based on their race, class, ability, sexuality, and other characteristics.",
"Radical feminism is a philosophy emphasizing the patriarchal roots of inequality between men and women, or, more specifically, the social domination of women by men.",
"Feminism is a multifaceted movement that focuses on topics that affect many aspects of our lives, such as reproductive rights, workplace culture, and caregiving.",
"Feminism is a social and political movement.",
"Feminism is about changing the way that people see male and female rights, and campaigning for equal ones.",
"Somebody who follows feminism is called a feminist.",
"New feminism is a form of feminism that emphasizes the integral complementarity of women and men, rather than the superiority of men over women or women over men, and advocates for respecting persons from conception to natural death.",
"Ecofeminism is a term that encompasses various theories and movements that explore the connections between gender, ecology, and social justice.",
"Lipstick feminism is a movement created of the third wave of feminism, following second wave feminism.",
"Socialist feminism is a two-pronged theory that broadens Marxist feminism 's argument for the role of capitalism in the oppression of women and radical feminism 's theory of the role of gender and the patriarchy.",
"Feminism is an outdated, misdirected ideology that perpetuates the very virtues it condemns and harms women much more than it helps them.",
"The meaning of FEMINISM is belief in and advocacy of the political, economic, and social equality of the sexes expressed especially through organized activity on behalf of women's rights and interests.",
"Radical feminism is a branch of feminism that seeks to dismantle the traditional patriarchal power and gender roles that keep women oppressed..",
"Feminism is a movement.",
"Everyday Feminism is an educational platform for personal and social liberation.",
"In simple terms, feminism is the advocacy for equal rights and opportunities for all genders.",
"Feminism is the result of people throughout history getting together to create and demand change so that girls and women would have rights equal to boys and men.",
"Feminism is generally thought of in the western world as comprising of three waves (early-to-mid 1800s-1960s, 1960s-late 1980s, late 1980s-present).",
"Feminism is the belief that men and women are politically and morally equal and should be treated as such legally and culturally.",
"Feminism is sexist.",
"The reason that feminism is primarily concerned with sexism that women face and not so much that men face is because women are the minority or the oppressed group.",
"Difference feminism is a term developed during the equality-versus-difference debate in American feminism to describe the view that men and women are different, but that no value judgment can be placed upon them and both sexes have equal moral status as persons.",
"Lesbian feminism is a term introduced in the United States in the 1960s.",
"Cyberfeminism is a sort of alliance that wants to defy any sort of boundaries of identity and definition and rather be truly postmodern in its potential for radical openness.",
"Feminism is a term that first came up in the 1900's.",
"Feminism is the theory; lesbianism is the practice-Attributed to Ti-Grace Atkinson.",
"Postcolonial feminism is a form of feminism that developed as a response to feminism focusing solely on the experiences of women in Western cultures and former colonies.",
"Feminism is defined in Merriam-Webster as 'the theory of the political, economic, and social equality of the sexes' and as the 'organized activity on behalf of women's rights and interests",
"Protofeminism is a concept that anticipates modern feminism in eras when the feminist concept as such was still unknown.",
"Feminism is a range of socio-political movements and ideologies that aim to define and establish the political, economic, personal, and social equality of the sexes.",
"Radical feminism is the most extreme form.",
"Feminism is for all women.",
"That is, true feminism is for all women, and it must be in order to be successful.",
"The first wave of feminism is believed to have ended once the 19th amendment was passed, granting women in ALL states the right to vote.",
"Grassroots feminism is a worldview and political practice rooted in the realities and interests of women, queer, trans, and non binary people who have been harmed by the intersecting forces of patriarchy, white supremacy, and capitalism.",
"Feminism is a social movement.",
"Feminism is often misunderstood and debated in today's society.",
"Many assume that feminism is the belief that women desire greater power than men rather than equality.",
"Feminism is supporting women's rights in order to promote equality across genders.",
"Feminism is a powerful social and political movement that calls for economic, cultural, social, and political equality for women.",
"Feminism is 'the advocacy of women's rights on the ground of the equality of the sexes.'.",
"Feminism is a mass movement commenced by women of all groups to eradicate all forms of feminist oppressions by men that are prevailing in a patriarchal society.",
"Mainstream feminism is focused on encouraging educated middle-class women to 'lean in' and 'crack the glass ceiling' — in other words, to climb the corporate ladder.",
"Feminism is not just the belief that women and men deserve social, political, and economic equality.",
"Feminism is not just about eliminating gender-based discrimination.",
"Thus, in this concept, feminism is a movement where people of all genders can be feminists if they're willing to do the work to dismantle patriarchal oppression.",
"Feminism isn't a movement concerned with men's issues at all.",
"Radical feminism is a perspective within feminism that calls for a radical re-ordering of society in which male supremacy is eliminated in all social and economic contexts, while recognizing that women's experiences are also affected by other social divisions such as in race, class, and sexual orientation.",
"Modern feminism is getting embarrassing.",
"The core idea of Islamic feminism is the full equality of all Muslims, male and female alike, in both the public and private spheres.",
"Islamic feminism is more radical than secular feminism which called for equal rights in the public sphere but complimentary rights in the private sphere.",
"Feminism is, at heart, a movement against domination.",
"Feminism is a movement against violence.",
"By definition, feminism is the advocacy of women's rights on the basis of having equality of the sexes.",
"Feminism is the doctrine advocating social, political, and economic rights for women equal to those of men.",
"First Wave Feminism is defined as the time period from 1848 to 1920.",
"Social justice feminism is the practice of recognizing issues of oppression dealing with race, class, sexuality, and citizenship and challenging them through practice rather than theory.",
"On this and other continents, however, feminism is also history and even memory'.",
"Feminism is one of the best ideas out there.",
"Feminism is something that would make the world a better place for everyone; not just for women.",
"At its core, feminism is a belief in the political, economic and social equality of the sexes.",
"Feminism is a socio-political and cultural movement that seeks to address and rectify inequalities faced by women.",
"Anna Pak (freshman, psychology) In a simple sentence, feminism is advocacy for women's equality.",
"However, feminism is also the inherent shared experiences and the respect for differences that women may have across gender, background, identity, and knowledge.",
"The third lie of feminism is that the more a woman achieves, the more attractive and desirable she becomes to men.",
"Feminism is still seen as elitist in a country where the majority of the population is rural and has 'grassroots' issues to deal with.",
"Analytical feminism is a line of philosophy that applies analytic concepts and methods to feminist issues and applies feminist concepts and insights to issues that have traditionally been of interest to analytic philosophers.",
"Feminism is a political and social movement or ideology that strives for political, economic and social equality of the sexes.",
"Feminism is not dead.",
"Feminism is still vibrant, despite declarations that it is over.",
"Feminism is a success, although many gender inequalities remain.",
"Feminism is taking powerful new forms, which makes it unrecognisable to some.",
"In The Future of Feminism, Sylvia Walby offers a provocative riposte to the notion that feminism is dead."]